eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
spring:
  main:
    web-application-type: reactive
  application:
    name: hello-security
  cloud:
    gateway:
      routes:
        - id: eureka-client-login
          uri: lb://eureka-client
          predicates:
            - Path=/api/v1/login/**
        - id: eureka-client-swagger
          uri: lb://eureka-client
          predicates:
            - Path=/swagger-ui/**
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

